### ISSUE TITLE
Crash Trying to Play Online on The Bomb: Dockyard

### ISSUE THREAD

**Issue by Chaoxufurwa** [erushinj/moon-alarmingly-streamlined-spawngroups#9]
[crash.txt](https://github.com/erushinj/moon-alarmingly-streamlined-spawngroups/files/15066024/crash.txt)

Found a crash while trying to play online on **The Bomb: Dockyard** after the most recent update to the mod. Went away after disabling it, but I have no clue if it was due to a mod conflict, or something else. The vast majority of the log, was the following two lines repeated just under 5030 times.

```
original() @mods/moon-alarmingly-streamlined-spawngroups-master/lua/elementspawncivilian.lua:115
produce_original() @mods/base/req/core/Hooks.lua:260
```

**Comment by erushinj** [comment]
Didn't see this earlier, sorry

This should be fixed in the latest version of the mod
